### ISSUE TITLE
Too many addresses?

### ISSUE THREAD

**Issue by gorsat** [sparkfun/Qwiic_VL53L1X_Py#3]
I was seeing bizarre behavior where my lone ToF was showing up as multiple devices in qwiic.list_devices (and consequently seeing the class instantiated multiple times for the same sensor). After spelunking the code I discovered a couple of things: 

1. my pi servo phat registers two addresses on the I2C bus that I wasn't aware of.
2. my ToF sensor registers for 112 (!!) addresses. The qwiic class happily considers the VL53L1X to be the device for any/all of those addresses that are seen active on the bus. In my case, these are the two used by the phat board in addition to the one that the ToF is really using. Hence, I end up with 3 instances of the ToF class. Yuck.

I can't for the life of me figure out why this class should be registering for 112 addresses. Doesn't this make it basically incompatible with the sparkfun python qwiic implementation which is obviously very dependent on there being (at least initially) a deterministic mapping between I2C address and device type? Doesn't this class just stomp on other devices' available_addresses depending on the order the modules are loaded? 

Seems like the fix is to just remove this line: 
_AVAILABLE_I2C_ADDRESS.extend(_FULL_ADDRESS_LIST)

**Comment by gorsat** [comment]
btw, in case anyone else has run in to this issue, here's the workaround I'm currently using:

`        # wipe out the existing available_devices list
        qwiic._QwiicInternal.available_devices = {}
        # modify the ToF sensor's entry in the device list so it doesn't
        # claim all addresses!
        for dev_class in qwiic._QwiicInternal.qwiic_devices:
            if 41 in dev_class.available_addresses:
                dev_class.available_addresses = [41]
        # reload the available_devices list
        qwiic._QwiicInternal.get_available_devices()
`

Then you can call qwiic.list_devices(), etc. and get the results you'd expect.

**Comment by santaimpersonator** [comment]
Hey there, so I believe your issue is in the implementation of `qwiic.list_devices` and not this Python package specifically.

When we first started developing the the `sparkfun-qwiic` python package, that method seemed like a useful feature. However, as we expanded on the number of products implemented in it, we ran into some unforeseen issues with that method. Specifically, I2C peripherals with configurable a I2C address, to any address. The private variable `_AVAILABLE_I2C_ADDRESS` lists all possible I2C addresses that the sensor can be configured for with the initial address being the default.

Unfortunately, while our proposed change would provide a quick fix to *your* problem, it would break the change I2C address method for this package. We are looking to fix the implementation of `qwiic.list_devices`; however, due to the complexity of what we would like to happen, it will take some time to work out the implementation. For now, that method will be unusable until we fix it.

(*\*As this isn't an actual issue with the VL53L1X Python package, I will be closing this issue.*)
